config/routes.rb
Rails.application.routes.draw do
  resources :lists do 
    resources :items do
      member do 
        put 'complete'
      end
    end
  end
  
  
  root'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, :dependent => :destroy
  accepts_nested_attributes_for :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @recent_lists = List.order('created_at DESC').limit(5)
  end

  # def recent_list_id
  #   @list = List.find(param[:list_id])
  # end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def create
    @list = List.find(params[:list_id])
    @list.items.create(item_params)
    redirect_to @list, notice: 'Item Added'
  end

  def new
    @item = Item.new
  end

  def update

  end

  # def complete
  #   @list = List.find(params[:list_id])
  #   @list.items.update_attributes(is_complete: true)
  #   redirect_to list_path notice: "Item Completed"
  # end
  def complete
    @list = List.find(params[:list_id])
    @item = Item.find(params[:id])
    @item.update_attributes(is_complete: true)
    redirect_to list_path(@list), notice: "Item completed"
  end

  def destroy
    @list = List.find(params[:list_id])
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to list_path(@list), notice: 'Item Deleted'
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:task, :due_date, :is_complete, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def create
    @list = List.create(list_params)
    if @list.save
      redirect_to list_path(@list), notice: 'Your list was successfuly created'
    else 
      render :new
    end 
  end

  def new
    @list = List.new
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to@list, notice: 'Review was successfuly updated' 
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path(@list), notice: 'List Deleted'
  end

  def show
    @list = List.find(params[:id])
    @items = @list.items.order(:created_at)
  end

  private

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def completed(item)
    item.is_complete ? 'x' : ' '
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Here Are Your Latest Lists</h2>

<div class="table-responsive" id="recent_lists">
  <% @recent_lists.each do |list| %>
  <table class="table table-striped table-hover">
    <thead>
        <h4 class="text-center"><%= link_to "#{list.name}", list_path(list) %></h4>
      <tr>
        <th></th>
        <th>Items</th>
        <th>Due</th>
      </tr>
    </thead>
    <% list.items.each do |item| %>
    <tbody>
      <tr>
        <td class="text-left">
          <% unless item.is_complete %>
              <%= link_to complete_list_item_path(list, item), method: 'put' do %><i class="fa fa-circle-o"></i>
                <% end %>
            <% else %>
              <i class="fa fa-check-circle"></i>
            <% end %>
        </td>
        <td class="text-left"><%= item.task %></td>
        <td class="text-left"><%= item.due_date.strftime("%D") %></td>
      </tr>
    </tbody>
    <% end %>
  </table>

  <% end %>
</div>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize@item.errors.count, "error" %>   prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.collection_select(:list_id, List.all, :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :due %>
    <%= f.date_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>ToDo's</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->
  <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav id="customize_nav" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul id="todo_navlinks" class="nav navbar-nav">
          <li><a href="/">Home</a></li>
          <li><%= link_to 'All Lists', lists_path %></li>
          <li><%= link_to 'New List', new_list_path %></li>
        </ul>
        <span class="todo_logo" ><h3 id="logo_heading"><a href="/">Todo's</a></h3></span>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
    <div id="contents">
      <%= yield %>
    </div>

    </div>
  </div>
  
  <div id="footer">
    <div class="footer">
      <div class="footer_text">
        <p class="muted credit"> a jlistens app </p>
      </div>
    </div>
  </div>
  
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize@list.errors.count, "error" %>   prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<H1>ToDo Lists</H1>

<div id="lists_index">
  <ul class="todo_list row">
    <% @lists.each do |list| %>
      <li class="col-xs-4">
        <h3><%= link_to "#{list.name}", list_path(list) %></h3>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to 'Make A New List', new_list_path %>

app/views/lists/new.html.erb
<h3>Please add a name for your new list</h3>

<%= render 'form' %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>


<span id="show_list"><%= @list.name %><%= link_to list_path(@list), method: 'delete' do %><i id="list_trash" class="fa fa-trash"></i>
  <% end %></span>
  <div id="bottom_space">
    <div id="recent_lists">
      <ul class="list_items">
        <% @list.items.each do |item| %>
          <li id="list_show">
            <% unless item.is_complete %>
              <%= link_to complete_list_item_path(@list, item), method: 'put' do %><i class="fa fa-circle-o"></i>
                <% end %>
            <% else %>
              <i class="fa fa-check-circle"></i>
            <% end %>
            <%= item.task %>
            <%= item.due_date.strftime("due %D") %>
            <%= link_to list_item_path(@list, item), method: 'delete' do %><i class="fa fa-trash"></i>
                <% end  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

<%= form_for(@list.items.new, :url => list_items_path(@list)) do |f| %>
  <%= hidden_field_tag :list_id, @list.id %>
  
  <div class="field">
    <%= f.label :New_Task %><br>
    <%= f.text_field :task %>
  </div>

  <div class="field">
    <%= f.label :due %>
    <%= f.date_select :due_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 